#include <vivid/audio/clap.h>
#include <vivid/operator_registry.h>
#include <vivid/audio_graph.h>
#include <vivid/context.h>

#include <cmath>

namespace vivid::audio {

REGISTER_OPERATOR_EX(Clap, "Audio Drums", "Hand clap with multiple noise bursts", false, vivid::OutputKind::Audio);

void Clap::init(Context& ctx) {
    m_sampleRate = AUDIO_SAMPLE_RATE;
    allocateOutput();
    m_filter.init(m_sampleRate);
    m_filter.setMode(dsp::SVFFilter::Mode::Bandpass);
    m_tailFilter.init(m_sampleRate);
    m_tailFilter.setMode(dsp::SVFFilter::Mode::Bandpass);
    reset();
    m_initialized = true;
}

void Clap::process(Context& ctx) {
    // In pull-based mode, audio is generated by generateBlock() on the audio thread.
    if (!m_initialized) return;
}

void Clap::generateBlock(uint32_t frameCount) {
    if (!m_initialized) return;

    if (m_output.frameCount != frameCount) {
        m_output.resize(frameCount);
    }

    float decayTime = static_cast<float>(decay) * m_sampleRate;
    float toneAmt = static_cast<float>(tone);
    float tailAmt = static_cast<float>(tail);
    float stereoAmt = static_cast<float>(stereoWidth);
    float tuneHz = static_cast<float>(tune);
    float vol = static_cast<float>(volume);

    float decayRate = (decayTime > 0) ? (1.0f / decayTime) : 1.0f;

    // Configure filters
    float filterFreq = tuneHz + toneAmt * 1000.0f;  // tune + brightness adjustment
    m_filter.setCutoff(filterFreq);
    m_filter.setResonance(0.4f);

    // Tail filter is slightly lower for body
    m_tailFilter.setCutoff(filterFreq * 0.7f);
    m_tailFilter.setResonance(0.3f);

    for (uint32_t i = 0; i < frameCount; ++i) {
        float sampleL = 0.0f;
        float sampleR = 0.0f;

        // Sum all burst envelopes with stereo placement
        for (int b = 0; b < NUM_BURSTS; ++b) {
            if (m_samplesSinceTrigger >= m_burstDelay[b] && m_burstEnv[b] > 0.0001f) {
                float noise = generateNoise();
                float burstSample = noise * m_burstEnv[b];

                // Apply stereo panning based on burst position
                float pan = m_burstPan[b] * stereoAmt;
                float gainL = 1.0f - std::max(0.0f, pan);   // Reduce left for right pan
                float gainR = 1.0f - std::max(0.0f, -pan);  // Reduce right for left pan

                sampleL += burstSample * gainL;
                sampleR += burstSample * gainR;

                // Decay each burst independently (fast attack for snap)
                m_burstEnv[b] *= 0.99f;
            }
        }

        // Bandpass filter for clap character
        float monoSample = (sampleL + sampleR) * 0.5f;
        float filtered = m_filter.process(monoSample) * 3.0f;

        // Add filtered noise tail
        if (tailAmt > 0.0f && m_tailEnv > 0.0001f) {
            float tailNoise = generateNoise() * m_tailEnv * tailAmt;
            float tailFiltered = m_tailFilter.process(tailNoise) * 2.0f;
            filtered += tailFiltered;
        }

        // Apply overall envelope
        filtered *= m_env * vol;

        // Mix stereo spread back in
        if (stereoAmt > 0.0f) {
            sampleL = filtered * (1.0f - stereoAmt * 0.5f) + m_filter.process(sampleL) * stereoAmt * 0.5f * m_env * vol * 3.0f;
            sampleR = filtered * (1.0f - stereoAmt * 0.5f) + m_filter.process(sampleR) * stereoAmt * 0.5f * m_env * vol * 3.0f;
        } else {
            sampleL = filtered;
            sampleR = filtered;
        }

        // Output
        m_output.samples[i * 2] = sampleL;
        m_output.samples[i * 2 + 1] = sampleR;

        // Advance time
        m_samplesSinceTrigger++;

        // Decay envelopes
        m_env *= (1.0f - decayRate * 0.2f);
        m_tailEnv *= (1.0f - decayRate * 0.15f);  // Tail decays slightly slower
    }
}

void Clap::handleEvent(const AudioEvent& event) {
    // Let base class handle Trigger -> onTrigger()
    AudioOperator::handleEvent(event);

    // Handle additional event types
    if (event.type == AudioEventType::Reset) {
        reset();
    }
}

void Clap::cleanup() {
    releaseOutput();
    m_initialized = false;
}

void Clap::midiNoteOn(uint8_t /*note*/, float velocity, uint8_t /*channel*/) {
    m_velocity = velocity;
    m_env = velocity;
    m_tailEnv = velocity;
    m_samplesSinceTrigger = 0;

    float sloppyAmt = static_cast<float>(sloppy);

    // Set up burst delays (sloppy determines timing between bursts)
    // Base spacing: ~10-30ms between bursts
    uint32_t baseSpacing = static_cast<uint32_t>(m_sampleRate * 0.015f);  // 15ms base
    uint32_t sloppyRange = static_cast<uint32_t>(m_sampleRate * 0.02f * sloppyAmt);  // 0-20ms variation

    m_burstDelay[0] = 0;
    m_burstEnv[0] = velocity;

    for (int b = 1; b < NUM_BURSTS; ++b) {
        // Add some randomness to timing
        uint32_t variation = (m_seed >> (b * 3)) % (sloppyRange + 1);
        m_burstDelay[b] = m_burstDelay[b - 1] + baseSpacing + variation;
        m_burstEnv[b] = velocity;
    }

    // Set up stereo panning for each burst (spread across stereo field)
    m_burstPan[0] = -0.5f;  // Left-ish
    m_burstPan[1] = 0.3f;   // Right-ish
    m_burstPan[2] = -0.2f;  // Slightly left
    m_burstPan[3] = 0.4f;   // Right

    // Randomize seed for next trigger
    m_seed ^= m_seed << 13;
    m_seed ^= m_seed >> 17;
    m_seed ^= m_seed << 5;
}

void Clap::midiNoteOff(uint8_t /*note*/, float /*velocity*/, uint8_t /*channel*/) {
    // One-shot drum, nothing to do
}

void Clap::onTrigger() {
    midiNoteOn(0, 1.0f, 0);
}

void Clap::reset() {
    m_env = 0.0f;
    m_tailEnv = 0.0f;
    m_samplesSinceTrigger = 0;
    for (int b = 0; b < NUM_BURSTS; ++b) {
        m_burstEnv[b] = 0.0f;
        m_burstDelay[b] = 0;
        m_burstPan[b] = 0.0f;
    }
    m_filter.reset();
    m_tailFilter.reset();
}

float Clap::generateNoise() {
    m_seed ^= m_seed << 13;
    m_seed ^= m_seed >> 17;
    m_seed ^= m_seed << 5;
    return (static_cast<float>(m_seed) / 2147483648.0f) - 1.0f;
}

bool Clap::drawVisualization(VizDrawList* dl, float minX, float minY, float maxX, float maxY) {
    VizVec2 min(minX, minY);
    VizVec2 max(maxX, maxY);
    float width = maxX - minX;
    float height = maxY - minY;

    // Dark magenta background
    dl->AddRectFilled(min, max, VIZ_COL32(50, 30, 45, 255), 4.0f);

    // Draw 4 burst bars
    float barW = (width - 20) / 4.0f;
    float maxBarH = height * 0.75f;

    for (int i = 0; i < NUM_BURSTS; i++) {
        float burstEnv = m_burstEnv[i];
        float barH = maxBarH * burstEnv;
        float barX = min.x + 6 + i * (barW + 2);

        // Pink/magenta gradient based on intensity
        uint32_t burstColor = VIZ_COL32(
            200 + (int)(55 * burstEnv),
            80 + (int)(100 * burstEnv),
            180, 255);

        dl->AddRectFilled(
            VizVec2(barX, max.y - 4 - barH),
            VizVec2(barX + barW - 2, max.y - 4),
            burstColor, 2.0f);
    }

    return true;
}

} // namespace vivid::audio
