#include <vivid/audio/hihat.h>
#include <vivid/operator_registry.h>
#include <vivid/audio_graph.h>
#include <vivid/context.h>

#include <cmath>

namespace vivid::audio {

REGISTER_OPERATOR_EX(HiHat, "Audio Drums", "Hi-hat with metallic ring and noise", false, vivid::OutputKind::Audio);

void HiHat::init(Context& ctx) {
    m_sampleRate = AUDIO_SAMPLE_RATE;
    allocateOutput();
    m_filter1.init(m_sampleRate);
    m_filter2.init(m_sampleRate);
    m_filter1.setMode(dsp::SVFFilter::Mode::Highpass);
    m_filter2.setMode(dsp::SVFFilter::Mode::Highpass);
    reset();
    m_initialized = true;
}

void HiHat::process(Context& ctx) {
    // In pull-based mode, audio is generated by generateBlock() on the audio thread.
    // process() is only called on the main thread for visual updates.
    if (!m_initialized) return;
}

void HiHat::generateBlock(uint32_t frameCount) {
    if (!m_initialized) return;

    if (m_output.frameCount != frameCount) {
        m_output.resize(frameCount);
    }

    float decayTime = static_cast<float>(decay) * m_sampleRate;
    float toneAmt = static_cast<float>(tone);
    float ringAmt = static_cast<float>(ring);
    float pitchMult = static_cast<float>(pitch);
    float attackTime = static_cast<float>(attack);
    float vol = static_cast<float>(volume);

    float decayRate = (decayTime > 0) ? (1.0f / decayTime) : 1.0f;

    // Attack envelope for filter sweep
    uint32_t attackSamples = static_cast<uint32_t>(attackTime * m_sampleRate);
    float attackRate = (attackSamples > 0) ? (1.0f / attackSamples) : 0.0f;

    // Ring oscillator frequencies (metallic hi-hat character)
    const float baseRingFreqs[6] = {205.3f, 304.4f, 369.6f, 522.7f, 540.0f, 800.0f};

    // Configure filters
    float baseCutoff = 4000.0f + toneAmt * 8000.0f;  // 4-12kHz
    m_filter1.setResonance(0.2f);
    m_filter2.setResonance(0.0f);

    for (uint32_t i = 0; i < frameCount; ++i) {
        // Generate noise based on type
        float noise;
        if (m_noiseType == NoiseType::Pink) {
            noise = generatePinkNoise();
        } else {
            noise = generateNoise();
        }

        // Add metallic ring (sum of square waves at inharmonic frequencies)
        float ringSample = 0.0f;
        if (ringAmt > 0.0f) {
            for (int r = 0; r < 6; ++r) {
                float freq = baseRingFreqs[r] * pitchMult;
                float phaseInc = freq / m_sampleRate;
                ringSample += (m_ringPhase[r] < 0.5f) ? 1.0f : -1.0f;
                m_ringPhase[r] += phaseInc;
                if (m_ringPhase[r] >= 1.0f) m_ringPhase[r] -= 1.0f;
            }
            ringSample /= 6.0f;
        }

        // Mix noise and ring
        float sample = noise * (1.0f - ringAmt * 0.5f) + ringSample * ringAmt;

        // Update filter envelope (for attack)
        if (m_attackSample < attackSamples) {
            m_filterEnv = static_cast<float>(m_attackSample) * attackRate;
            m_attackSample++;
        } else {
            m_filterEnv = 1.0f;
        }

        // Apply filter cutoff with envelope
        float cutoff = baseCutoff * m_filterEnv;
        m_filter1.setCutoff(std::max(100.0f, cutoff));

        // Apply SVF highpass filter(s)
        sample = m_filter1.process(sample);

        if (m_filterSlope == FilterSlope::Slope24dB) {
            m_filter2.setCutoff(std::max(100.0f, cutoff));
            sample = m_filter2.process(sample);
        }

        // Apply amplitude envelope
        sample *= m_env * vol;

        // Output
        m_output.samples[i * 2] = sample;
        m_output.samples[i * 2 + 1] = sample;

        // Decay envelope (exponential)
        m_env *= (1.0f - decayRate * 0.3f);
    }
}

void HiHat::handleEvent(const AudioEvent& event) {
    // Let base class handle Trigger -> onTrigger()
    AudioOperator::handleEvent(event);

    // Handle additional event types
    switch (event.type) {
        case AudioEventType::NoteOff:
            choke();
            break;
        case AudioEventType::Reset:
            reset();
            break;
        default:
            break;
    }
}

void HiHat::cleanup() {
    releaseOutput();
    m_initialized = false;
}

void HiHat::midiNoteOn(uint8_t /*note*/, float velocity, uint8_t /*channel*/) {
    m_velocity = velocity;
    m_env = velocity;
    m_filterEnv = 0.0f;
    m_attackSample = 0;
}

void HiHat::midiNoteOff(uint8_t /*note*/, float /*velocity*/, uint8_t /*channel*/) {
    // Note-off chokes the hi-hat (for open→closed transitions)
    choke();
}

void HiHat::choke() {
    m_env = 0.0f;
}

void HiHat::reset() {
    m_env = 0.0f;
    m_filterEnv = 0.0f;
    m_attackSample = 0;
    for (int i = 0; i < 6; ++i) m_ringPhase[i] = 0.0f;
    for (int i = 0; i < 16; ++i) m_pinkRows[i] = 0.0f;
    m_pinkIndex = 0;
    m_pinkRunningSum = 0.0f;
    m_filter1.reset();
    m_filter2.reset();
}

float HiHat::generateNoise() {
    m_seed ^= m_seed << 13;
    m_seed ^= m_seed >> 17;
    m_seed ^= m_seed << 5;
    return (static_cast<float>(m_seed) / 2147483648.0f) - 1.0f;
}

float HiHat::generatePinkNoise() {
    // Voss-McCartney algorithm for pink noise
    // Uses 16 random values updated at different rates
    float white = generateNoise();

    m_pinkIndex = (m_pinkIndex + 1) & 15;

    // Update rows based on trailing zeros in index
    if (m_pinkIndex != 0) {
        int numZeros = 0;
        int n = m_pinkIndex;
        while ((n & 1) == 0) {
            numZeros++;
            n >>= 1;
        }

        m_pinkRunningSum -= m_pinkRows[numZeros];
        float newRandom = generateNoise();
        m_pinkRunningSum += newRandom;
        m_pinkRows[numZeros] = newRandom;
    }

    // Sum and normalize
    return (m_pinkRunningSum + white) * 0.0625f;  // /16 for normalization
}

bool HiHat::drawVisualization(VizDrawList* dl, float minX, float minY, float maxX, float maxY) {
    VizVec2 min(minX, minY);
    VizVec2 max(maxX, maxY);
    float width = maxX - minX;
    float height = maxY - minY;
    float cx = (minX + maxX) * 0.5f;
    float cy = (minY + maxY) * 0.5f;

    // Dark cyan background
    dl->AddRectFilled(min, max, VIZ_COL32(30, 45, 50, 255), 4.0f);

    float env = m_env;

    // Draw metallic shimmer lines radiating from center
    int numRays = 8;
    float maxRadius = std::min(width, height) * 0.4f;
    float radius = maxRadius * env;

    for (int i = 0; i < numRays; i++) {
        float angle = (i / (float)numRays) * TWO_PI;
        float r1 = radius * 0.3f;
        float r2 = radius;
        uint32_t rayColor = VIZ_COL32(
            150 + (int)(105 * env),
            200 + (int)(55 * env),
            220, (int)(200 * env));
        dl->AddLine(
            VizVec2(cx + r1 * std::cos(angle), cy + r1 * std::sin(angle)),
            VizVec2(cx + r2 * std::cos(angle), cy + r2 * std::sin(angle)),
            rayColor, 1.5f + env);
    }

    // Center dot
    dl->AddCircleFilled(VizVec2(cx, cy), 3.0f + env * 4.0f,
        VIZ_COL32(200, 240, 255, (int)(255 * env)));

    return true;
}

} // namespace vivid::audio
