#include <vivid/audio/kick.h>
#include <vivid/operator_registry.h>
#include <vivid/audio_graph.h>
#include <vivid/context.h>
#include <vivid/viz_helpers.h>

#include <cmath>

namespace vivid::audio {

REGISTER_OPERATOR_EX(Kick, "Audio Drums", "808-style kick drum with pitch envelope", false, vivid::OutputKind::Audio);

void Kick::init(Context& ctx) {
    m_sampleRate = AUDIO_SAMPLE_RATE;
    allocateOutput();
    reset();
    m_initialized = true;
}

void Kick::process(Context& ctx) {
    // In pull-based mode, audio is generated by generateBlock() on the audio thread.
    // process() is only called on the main thread for visual updates.
    if (!m_initialized) return;
}

void Kick::generateBlock(uint32_t frameCount) {
    if (!m_initialized) return;

    // Resize buffer if needed
    if (m_output.frameCount != frameCount) {
        m_output.resize(frameCount);
    }

    float basePitch = static_cast<float>(pitch);
    float pitchEnvAmt = static_cast<float>(pitchEnv);
    float pitchDecayTime = static_cast<float>(pitchDecay) * m_sampleRate;
    float ampDecayTime = static_cast<float>(decay) * m_sampleRate;
    float clickAmt = static_cast<float>(click);
    float driveAmt = static_cast<float>(drive);
    float overtoneAmt = static_cast<float>(overtones);
    float attackTime = static_cast<float>(attack);
    float vol = static_cast<float>(volume);

    float pitchDecayRate = (pitchDecayTime > 0) ? (1.0f / pitchDecayTime) : 1.0f;
    float ampDecayRate = (ampDecayTime > 0) ? (1.0f / ampDecayTime) : 1.0f;
    float clickDecaySamples = m_sampleRate * 0.002f;  // 2ms = ~96 samples at 48kHz
    float clickDecayRate = 1.0f / clickDecaySamples;

    // Attack envelope: fade-in time
    uint32_t attackSamples = static_cast<uint32_t>(attackTime * m_sampleRate);
    float attackRate = (attackSamples > 0) ? (1.0f / attackSamples) : 0.0f;

    for (uint32_t i = 0; i < frameCount; ++i) {
        // Compute current frequency (pitch envelope)
        float freq = basePitch + pitchEnvAmt * m_pitchEnvValue;
        float phaseInc = freq / m_sampleRate;

        // Generate fundamental sine oscillator
        float osc = std::sin(m_phase * TWO_PI);

        // Add overtones (2nd and 3rd harmonics)
        if (overtoneAmt > 0.0f) {
            // 2nd harmonic at ~0.5x level, 3rd at ~0.25x level
            float harm2 = std::sin(m_phase2 * TWO_PI) * 0.5f;
            float harm3 = std::sin(m_phase3 * TWO_PI) * 0.25f;
            osc = osc * (1.0f - overtoneAmt * 0.4f) + (harm2 + harm3) * overtoneAmt;
        }

        // Generate click (short noise burst)
        float clickSample = 0.0f;
        if (m_clickEnv > 0.0f && clickAmt > 0.0f) {
            // Simple noise for click
            uint32_t seed = static_cast<uint32_t>(m_phase * 1000000.0f) ^ 0x5DEECE66D;
            seed ^= seed << 13;
            seed ^= seed >> 17;
            seed ^= seed << 5;
            clickSample = ((seed / 2147483648.0f) - 1.0f) * m_clickEnv * clickAmt;
        }

        // Mix and apply envelope with attack
        float sample = (osc + clickSample) * m_ampEnv * m_attackEnv;

        // Apply soft saturation/drive
        if (driveAmt > 0.0f) {
            sample = softClip(sample * (1.0f + driveAmt * 3.0f));
        }

        sample *= vol;

        // Output stereo
        m_output.samples[i * 2] = sample;
        m_output.samples[i * 2 + 1] = sample;

        // Advance phases (fundamental and harmonics)
        m_phase += phaseInc;
        if (m_phase >= 1.0f) m_phase -= 1.0f;

        m_phase2 += phaseInc * 2.0f;  // 2nd harmonic = 2x frequency
        if (m_phase2 >= 1.0f) m_phase2 -= 1.0f;

        m_phase3 += phaseInc * 3.0f;  // 3rd harmonic = 3x frequency
        if (m_phase3 >= 1.0f) m_phase3 -= 1.0f;

        // Update attack envelope (ramp up from 0 to 1)
        if (m_attackSample < attackSamples) {
            m_attackEnv = static_cast<float>(m_attackSample) * attackRate;
            m_attackSample++;
        } else {
            m_attackEnv = 1.0f;
        }

        // Decay envelopes (exponential)
        m_pitchEnvValue *= (1.0f - pitchDecayRate);
        m_ampEnv *= (1.0f - ampDecayRate);
        m_ampEnv = std::max(0.0f, m_ampEnv - ampDecayRate * 0.01f);
        m_clickEnv *= (1.0f - clickDecayRate);
    }
}

void Kick::handleEvent(const AudioEvent& event) {
    if (event.type == AudioEventType::Trigger) {
        float velocity = (event.value1 > 0.0f) ? event.value1 : 1.0f;
        midiNoteOn(0, velocity, 0);
    } else if (event.type == AudioEventType::Reset) {
        reset();
    }
}

void Kick::cleanup() {
    releaseOutput();
    m_initialized = false;
}

void Kick::midiNoteOn(uint8_t /*note*/, float velocity, uint8_t /*channel*/) {
    m_velocity = velocity;
    m_ampEnv = velocity;
    m_pitchEnvValue = 1.0f;
    m_clickEnv = velocity;
    m_attackEnv = 0.0f;  // Start at 0 for attack fade-in
    m_attackSample = 0;
    // Don't reset phase for punch
}

void Kick::midiNoteOff(uint8_t /*note*/, float /*velocity*/, uint8_t /*channel*/) {
    // One-shot drum, nothing to do
}

void Kick::reset() {
    m_phase = 0.0f;
    m_phase2 = 0.0f;
    m_phase3 = 0.0f;
    m_ampEnv = 0.0f;
    m_pitchEnvValue = 0.0f;
    m_clickEnv = 0.0f;
    m_attackEnv = 1.0f;
    m_attackSample = 0;
}

float Kick::softClip(float x) const {
    // Tanh soft clipping
    if (x > 1.0f) return std::tanh(x);
    if (x < -1.0f) return std::tanh(x);
    return x;
}

bool Kick::drawVisualization(VizDrawList* dl, float minX, float minY, float maxX, float maxY) {
    VizHelpers viz(dl);
    VizBounds bounds{minX, minY, maxX - minX, maxY - minY};

    viz.drawBackground(bounds, VizColors::BackgroundDark);

    // Amplitude envelope bar
    VizBounds barBounds = bounds.inset(bounds.w * 0.2f, 4.0f);
    viz.drawEnvelopeBar(barBounds, m_ampEnv, VizColors::EnvelopeWarm);

    // Pitch indicator line
    if (m_pitchEnvValue > 0.01f) {
        float pitchY = bounds.y + 8 + (bounds.h - 16) * (1.0f - m_pitchEnvValue);
        dl->AddLine({barBounds.x - 4, pitchY}, {barBounds.right() + 4, pitchY},
                    VizColors::Active, 2.0f);
    }

    return true;
}

InspectData Kick::inspect() const {
    auto data = Operator::inspect();
    data.set("is_active", isActive() ? 1.0f : 0.0f);
    data.set("amp_env", m_ampEnv);
    data.set("pitch_env", m_pitchEnvValue);
    data.set("velocity", m_velocity);
    return data;
}

} // namespace vivid::audio
