#include <vivid/audio/oscillator.h>
#include <vivid/operator_registry.h>
#include <vivid/context.h>
#include <cmath>

namespace vivid::audio {

REGISTER_OPERATOR_EX(Oscillator, "Audio Synthesis", "Audio-rate oscillator for synthesis", false, vivid::OutputKind::Audio);

void Oscillator::init(Context& ctx) {
    m_sampleRate = AUDIO_SAMPLE_RATE;
    allocateOutput();
    m_phaseL = 0.0f;
    m_phaseR = 0.0f;
    snapParams();  // Jump to initial values without ramp
    m_initialized = true;
}

void Oscillator::process(Context& ctx) {
    // In pull-based mode, audio is generated by generateBlock() on the audio thread.
    // process() is only called on the main thread for visual updates.
    if (!m_initialized) return;
}

void Oscillator::generateBlock(uint32_t frameCount) {
    if (!m_initialized) return;

    // Resize buffer if needed
    if (m_output.frameCount != frameCount) {
        m_output.resize(frameCount);
    }

    // Block-rate smoothing for volume, detune, pulseWidth, stereoDetune
    volume.advance(frameCount);
    detune.advance(frameCount);
    pulseWidth.advance(frameCount);
    stereoDetune.advance(frameCount);

    float vol = volume;
    float detuneVal = detune;
    float stereoDetuneVal = stereoDetune;
    float detuneRatio = centsToRatio(detuneVal);

    // Stereo detune ratio (block-rate is fine for stereo spread)
    float stereoRatioL = 1.0f;
    float stereoRatioR = 1.0f;
    if (stereoDetuneVal > 0.0f) {
        float r = centsToRatio(stereoDetuneVal);
        stereoRatioL = 1.0f / r;
        stereoRatioR = r;
    }

    for (uint32_t i = 0; i < frameCount; ++i) {
        // Per-sample smoothing for frequency (prevents clicks on pitch changes)
        float baseFreq = frequency.tick();

        float freqL = baseFreq * detuneRatio * stereoRatioL;
        float freqR = baseFreq * detuneRatio * stereoRatioR;

        float phaseIncL = freqL / static_cast<float>(m_sampleRate);
        float phaseIncR = freqR / static_cast<float>(m_sampleRate);

        // Generate samples
        float sampleL = generateSample(m_phaseL) * vol;
        float sampleR = generateSample(m_phaseR) * vol;

        // Write to interleaved buffer
        m_output.samples[i * 2] = sampleL;
        m_output.samples[i * 2 + 1] = sampleR;

        // Advance phases (wrap at 1.0)
        m_phaseL += phaseIncL;
        m_phaseR += phaseIncR;

        if (m_phaseL >= 1.0f) m_phaseL -= 1.0f;
        if (m_phaseR >= 1.0f) m_phaseR -= 1.0f;
    }
}

void Oscillator::cleanup() {
    releaseOutput();
    m_initialized = false;
}

float Oscillator::generateSample(float phase) const {
    switch (m_waveform) {
        case Waveform::Sine:
            return std::sin(phase * TWO_PI);

        case Waveform::Triangle:
            // Triangle: ramp up 0->0.5, ramp down 0.5->1
            if (phase < 0.5f) {
                return 4.0f * phase - 1.0f;  // -1 to 1
            } else {
                return 3.0f - 4.0f * phase;  // 1 to -1
            }

        case Waveform::Square:
            return (phase < 0.5f) ? 1.0f : -1.0f;

        case Waveform::Saw:
            // Sawtooth: ramp from -1 to 1
            return 2.0f * phase - 1.0f;

        case Waveform::Pulse:
            // Variable pulse width (reads current smoothed value)
            return (phase < pulseWidth.get()) ? 1.0f : -1.0f;

        default:
            return 0.0f;
    }
}

float Oscillator::centsToRatio(float cents) const {
    // 100 cents = 1 semitone, 1200 cents = 1 octave
    // ratio = 2^(cents/1200)
    return std::pow(2.0f, cents / 1200.0f);
}

} // namespace vivid::audio
