#include <vivid/audio/snare.h>
#include <vivid/operator_registry.h>
#include <vivid/audio_graph.h>
#include <vivid/context.h>
#include <vivid/viz_helpers.h>

#include <cmath>

namespace vivid::audio {

REGISTER_OPERATOR_EX(Snare, "Audio Drums", "Snare drum with tone and noise", false, vivid::OutputKind::Audio);

void Snare::init(Context& ctx) {
    m_sampleRate = AUDIO_SAMPLE_RATE;
    allocateOutput();
    m_filter.init(m_sampleRate);
    reset();
    m_initialized = true;
}

void Snare::process(Context& ctx) {
    // In pull-based mode, audio is generated by generateBlock() on the audio thread.
    if (!m_initialized) return;
}

void Snare::generateBlock(uint32_t frameCount) {
    if (!m_initialized) return;

    if (m_output.frameCount != frameCount) {
        m_output.resize(frameCount);
    }

    float toneAmt = static_cast<float>(tone);
    float noiseAmt = static_cast<float>(noise);
    float freq = static_cast<float>(pitch);
    float toneDecayTime = static_cast<float>(toneDecay) * m_sampleRate;
    float noiseDecayTime = static_cast<float>(noiseDecay) * m_sampleRate;
    float snappyAmt = static_cast<float>(snappy);
    float colorAmt = static_cast<float>(color);
    float vol = static_cast<float>(volume);

    float toneDecayRate = (toneDecayTime > 0) ? (1.0f / toneDecayTime) : 1.0f;
    float noiseDecayRate = (noiseDecayTime > 0) ? (1.0f / noiseDecayTime) : 1.0f;
    float phaseInc = freq / m_sampleRate;

    // Configure SVF filter based on type
    switch (m_filterType) {
        case SnareFilterType::Highpass:
            m_filter.setMode(dsp::SVFFilter::Mode::Highpass);
            m_filter.setCutoff(2000.0f + snappyAmt * 4000.0f);  // 2-6kHz
            break;
        case SnareFilterType::Lowpass:
            m_filter.setMode(dsp::SVFFilter::Mode::Lowpass);
            m_filter.setCutoff(8000.0f - snappyAmt * 6000.0f);  // 8-2kHz
            break;
        case SnareFilterType::Bandpass:
            m_filter.setMode(dsp::SVFFilter::Mode::Bandpass);
            m_filter.setCutoff(1500.0f + snappyAmt * 3000.0f);  // 1.5-4.5kHz
            break;
    }
    m_filter.setResonance(0.3f);  // Mild resonance

    for (uint32_t i = 0; i < frameCount; ++i) {
        // Tone component (fundamental sine)
        float toneSample = std::sin(m_phase * TWO_PI);

        // Add harmonics based on color parameter
        // 2nd harmonic adds warmth, 3rd adds edge
        float harm2 = std::sin(m_phase2 * TWO_PI) * 0.5f;
        float harm3 = std::sin(m_phase3 * TWO_PI) * 0.25f;
        toneSample = toneSample * (1.0f - colorAmt * 0.5f) + (harm2 + harm3) * colorAmt;
        toneSample *= m_toneEnv * toneAmt;

        // Noise component
        float noiseSample = generateNoise();

        // Apply SVF filter to noise
        if (snappyAmt > 0.0f) {
            float filtered = m_filter.process(noiseSample);
            noiseSample = noiseSample * (1.0f - snappyAmt) + filtered * snappyAmt;
        }
        noiseSample *= m_noiseEnv * noiseAmt;

        // Mix
        float sample = (toneSample + noiseSample) * vol;

        // Output
        m_output.samples[i * 2] = sample;
        m_output.samples[i * 2 + 1] = sample;

        // Advance phases
        m_phase += phaseInc;
        if (m_phase >= 1.0f) m_phase -= 1.0f;

        m_phase2 += phaseInc * 2.0f;  // 2nd harmonic
        if (m_phase2 >= 1.0f) m_phase2 -= 1.0f;

        m_phase3 += phaseInc * 3.0f;  // 3rd harmonic
        if (m_phase3 >= 1.0f) m_phase3 -= 1.0f;

        // Decay envelopes (exponential)
        m_toneEnv *= (1.0f - toneDecayRate);
        m_noiseEnv *= (1.0f - noiseDecayRate * 0.5f);
    }
}

void Snare::handleEvent(const AudioEvent& event) {
    // Let base class handle Trigger -> onTrigger()
    AudioOperator::handleEvent(event);

    // Handle additional event types
    if (event.type == AudioEventType::Reset) {
        reset();
    }
}

void Snare::cleanup() {
    releaseOutput();
    m_initialized = false;
}

void Snare::midiNoteOn(uint8_t /*note*/, float velocity, uint8_t /*channel*/) {
    m_velocity = velocity;
    m_toneEnv = velocity;
    m_noiseEnv = velocity;
}

void Snare::midiNoteOff(uint8_t /*note*/, float /*velocity*/, uint8_t /*channel*/) {
    // One-shot drum, nothing to do
}

void Snare::reset() {
    m_phase = 0.0f;
    m_phase2 = 0.0f;
    m_phase3 = 0.0f;
    m_toneEnv = 0.0f;
    m_noiseEnv = 0.0f;
    m_filter.reset();
}

float Snare::generateNoise() {
    m_seed ^= m_seed << 13;
    m_seed ^= m_seed >> 17;
    m_seed ^= m_seed << 5;
    return (static_cast<float>(m_seed) / 2147483648.0f) - 1.0f;
}

bool Snare::drawVisualization(VizDrawList* dl, float minX, float minY, float maxX, float maxY) {
    VizHelpers viz(dl);
    VizBounds bounds{minX, minY, maxX - minX, maxY - minY};

    viz.drawBackground(bounds);
    viz.drawDualEnvelope(bounds.inset(4), m_toneEnv, m_noiseEnv,
                         VizColors::EnvelopeWarm, VizColors::TextPrimary);
    return true;
}

InspectData Snare::inspect() const {
    auto data = Operator::inspect();
    data.set("is_active", isActive() ? 1.0f : 0.0f);
    data.set("tone_env", m_toneEnv);
    data.set("noise_env", m_noiseEnv);
    data.set("velocity", m_velocity);
    return data;
}

} // namespace vivid::audio
