// Vivid Standalone Runtime — generated by `vivid export`
// Stripped-down version of main.cpp: no UI, no hot-reload, no editor.

#include "runtime/gpu_context.h"
#include "runtime/fullscreen_blit.h"
#include "runtime/operator_registry.h"
#include "runtime/graph.h"
#include "runtime/runtime_core.h"
#include "runtime/audio_engine.h"
#include "runtime/cadence_bridge.h"
#include "runtime/compiled_graph.h"
#include "runtime/runtime_api.h"
#include "runtime/builtin_operators.h"
#include "runtime/system_midi.h"
#include "operator_api/gpu_operator.h"
#include "operator_api/data_driven_filter.h"
#include "operator_api/types.h"
#include "common/gpu_util.h"
#include "embedded_graph.h"
#include <webgpu/webgpu.h>
#include <webgpu/wgpu.h>
#include <GLFW/glfw3.h>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

#ifdef VIVID_STANDALONE_CONTROL_SERVER
#include "runtime/control_server.h"
#endif

#ifdef __APPLE__
#include "runtime/macos_frame_timer.h"
#endif

// Forward declarations from generated files
void register_static_operators(vivid::OperatorRegistry& registry);
#ifdef VIVID_HAS_WGSL_PRESETS
void register_embedded_wgsl_presets(vivid::OperatorRegistry& registry);
#endif

using vivid::to_sv;

static constexpr uint32_t kDefaultTexW = 800;
static constexpr uint32_t kDefaultTexH = 600;
static constexpr WGPUTextureFormat kOffscreenFormat = WGPUTextureFormat_RGBA16Float;

static void emit_clear_pass(WGPUCommandEncoder encoder, WGPUTextureView view) {
    WGPURenderPassColorAttachment color{};
    color.view = view;
    color.loadOp = WGPULoadOp_Clear;
    color.storeOp = WGPUStoreOp_Store;
    color.clearValue = {0.0, 0.0, 0.0, 1.0};
    WGPURenderPassDescriptor desc{};
    desc.label = to_sv("Clear");
    desc.colorAttachmentCount = 1;
    desc.colorAttachments = &color;
    WGPURenderPassEncoder pass = wgpuCommandEncoderBeginRenderPass(encoder, &desc);
    wgpuRenderPassEncoderEnd(pass);
    wgpuRenderPassEncoderRelease(pass);
}

int main(int argc, char* argv[]) {
    // Parse minimal CLI
    std::string graph_override;
    bool headless = false;

    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--graph") == 0 && i + 1 < argc) {
            graph_override = argv[++i];
        } else if (std::strcmp(argv[i], "--headless") == 0) {
            headless = true;
        }
    }

    // --- GLFW ---
    if (!glfwInit()) {
        std::fprintf(stderr, "[standalone] Failed to init GLFW\n");
        return 1;
    }

    glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
    glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);
    if (headless) {
        glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
    }

    GLFWwindow* window = glfwCreateWindow(1280, 720, "Vivid", nullptr, nullptr);
    if (!window) {
        std::fprintf(stderr, "[standalone] Failed to create window\n");
        glfwTerminate();
        return 1;
    }

    // ESC to quit
    glfwSetKeyCallback(window, [](GLFWwindow* w, int key, int, int action, int) {
        if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
            glfwSetWindowShouldClose(w, GLFW_TRUE);
    });

    int fb_width, fb_height;
    glfwGetFramebufferSize(window, &fb_width, &fb_height);

    // --- GPU ---
    vivid::GpuContext gpu;
    if (!gpu.init(window, fb_width, fb_height)) {
        glfwDestroyWindow(window);
        glfwTerminate();
        return 1;
    }

    vivid::FullscreenBlit blit;
    if (!blit.init(gpu.device(), gpu.surface_format())) {
        std::fprintf(stderr, "[standalone] Failed to init blit pipeline\n");
        glfwDestroyWindow(window);
        glfwTerminate();
        return 1;
    }

    // --- Operator Registry ---
    vivid::OperatorRegistry registry;
    register_builtin_operators(registry);
    register_static_operators(registry);

#ifdef VIVID_HAS_WGSL_PRESETS
    register_embedded_wgsl_presets(registry);
#endif

    // --- Load Graph ---
    vivid::Graph graph;
    bool graph_loaded = false;

    if (!graph_override.empty()) {
        graph_loaded = graph.load(graph_override.c_str());
    } else {
        graph_loaded = graph.load_from_string(kEmbeddedGraphJSON);
    }

    if (!graph_loaded) {
        std::fprintf(stderr, "[standalone] Failed to load graph\n");
        glfwDestroyWindow(window);
        glfwTerminate();
        return 1;
    }

    // Register user filters from graph JSON (inline WGSL shaders)
    if (!graph.filters().empty()) {
        namespace fs = std::filesystem;
        auto tmp_dir = fs::temp_directory_path() / "vivid_standalone_filters";
        fs::create_directories(tmp_dir);

        for (const auto& fd : graph.filters()) {
            std::string working_path = (tmp_dir / (fd.name + ".wgsl")).string();
            { std::ofstream ofs(working_path); ofs << fd.shader; }

            auto config = std::make_shared<vivid::DataDrivenFilterConfig>();
            config->name = fd.name;
            config->shader_path = working_path;
            config->source_builtin = fd.source;
            config->time_dependent = fd.time_dependent;
            for (const auto& pd : fd.params) {
                vivid::DataDrivenFilterConfig::ParamDef cpd;
                cpd.name = pd.name;
                cpd.default_value = pd.default_value;
                cpd.min_value = pd.min_value;
                cpd.max_value = pd.max_value;
                config->params.push_back(std::move(cpd));
            }
            registry.register_user_filter(fd.name, config);
            std::fprintf(stderr, "[standalone] Registered user filter: %s\n", fd.name.c_str());
        }
    }

    // --- Build Runtime ---
    vivid::RuntimeCore runtime;
    if (!runtime.build(graph, registry)) {
        std::fprintf(stderr, "[standalone] Failed to build runtime\n");
        glfwDestroyWindow(window);
        glfwTerminate();
        return 1;
    }

    bool has_gpu_ops = runtime.has_gpu_operators();
    if (has_gpu_ops) {
        runtime.allocate_gpu_textures(gpu.device(), kDefaultTexW, kDefaultTexH, kOffscreenFormat);
    }
    int video_out_idx = has_gpu_ops ? runtime.find_gpu_sink() : -1;

    // --- Audio Engine ---
    vivid::AudioEngine audio_engine;
    bool has_audio = false;
    if (runtime.has_audio_operators()) {
        if (audio_engine.build(runtime)) {
            if (audio_engine.start()) {
                has_audio = true;
                std::fprintf(stderr, "[standalone] Audio engine started\n");
            }
        }
    }

    // --- MIDI ---
    vivid::SystemMidiListener system_midi;
    system_midi.open_all();

    // --- RuntimeAPI (for MIDI mappings, variations) ---
    vivid::RuntimeAPI runtime_api(graph, runtime, audio_engine, registry, &system_midi);

#ifdef VIVID_STANDALONE_CONTROL_SERVER
    vivid::ControlServer control_server;
    if (!control_server.start(9876)) {
        std::fprintf(stderr, "[standalone] Control server unavailable\n");
    }
#endif

    // --- Main Loop ---
    double prev_time = glfwGetTime();
    uint64_t frame_count = 0;

    auto tick_frame = [&]() -> bool {
        int fb_w, fb_h;
        glfwGetFramebufferSize(window, &fb_w, &fb_h);
        if (fb_w == 0 || fb_h == 0) return true;  // minimized

        if (fb_w != fb_width || fb_h != fb_height) {
            fb_width = fb_w;
            fb_height = fb_h;
            gpu.resize(static_cast<uint32_t>(fb_w), static_cast<uint32_t>(fb_h));
        }

#ifdef VIVID_STANDALONE_CONTROL_SERVER
        control_server.process_requests(runtime_api, graph, runtime, registry,
                                        has_gpu_ops, has_audio);
        if (runtime_api.has_pending()) {
            runtime_api.apply_pending(has_gpu_ops, has_audio);
            if (has_gpu_ops)
                runtime.allocate_gpu_textures(gpu.device(), kDefaultTexW, kDefaultTexH, kOffscreenFormat);
        }
#endif

        if (runtime.needs_gpu_realloc()) {
            runtime.allocate_gpu_textures(gpu.device(), kDefaultTexW, kDefaultTexH, kOffscreenFormat);
            runtime.clear_gpu_realloc();
        }

        double now = glfwGetTime();
        double dt = now - prev_time;
        prev_time = now;

        // Apply MIDI mappings
        runtime_api.apply_midi_mappings();
        runtime_api.tick_quantized_switch();

        // Begin frame
        vivid::FrameState frame;
        bool have_surface = gpu.begin_frame(frame);

        WGPUCommandEncoder tick_encoder = frame.encoder;
        if (!have_surface) {
            WGPUCommandEncoderDescriptor enc_desc{};
            enc_desc.label = to_sv("Offscreen");
            tick_encoder = wgpuDeviceCreateCommandEncoder(gpu.device(), &enc_desc);
        }

        // Build GPU state
        VividGpuContext gpu_state{};
        gpu_state.device          = gpu.device();
        gpu_state.queue           = gpu.queue();
        gpu_state.command_encoder = tick_encoder;
        gpu_state.output_format   = kOffscreenFormat;

        // Inject audio analysis
        if (has_audio)
            runtime.pre_tick_audio_sync(now);

        // Tick runtime
        runtime.tick(now, dt, frame_count, &gpu_state, nullptr);

        // Tick state presets
        runtime_api.tick_state_presets();

        // Push params to audio thread
        if (has_audio)
            runtime.post_tick_audio_sync();

        // Present
        if (have_surface) {
            if (has_gpu_ops && video_out_idx >= 0 && runtime.compiled_graph()) {
                const auto& vo_cn = runtime.compiled_graph()->nodes[video_out_idx];
                WGPUTextureView display_tex = nullptr;
                uint32_t src_w = 0, src_h = 0;

                if (!vo_cn.resolved_tex_inputs.empty()) {
                    display_tex = vo_cn.resolved_tex_inputs[0];
                    runtime.gpu_sink_source_size(video_out_idx, src_w, src_h);
                }

                if (display_tex && src_w > 0 && src_h > 0) {
                    auto fit_mode = vivid::FitMode::Fit;
                    auto fm_it = vo_cn.param_indices.find("fit_mode");
                    if (fm_it != vo_cn.param_indices.end())
                        fit_mode = static_cast<vivid::FitMode>(
                            static_cast<int>(vo_cn.param_values[fm_it->second]));

                    blit.blit_fit(frame.encoder, display_tex, frame.view,
                                  src_w, src_h,
                                  static_cast<uint32_t>(fb_width),
                                  static_cast<uint32_t>(fb_height),
                                  fit_mode, false);
                } else {
                    emit_clear_pass(frame.encoder, frame.view);
                }
            } else {
                emit_clear_pass(frame.encoder, frame.view);
            }

            gpu.end_frame(frame);
        } else {
            vivid::gpu_submit(gpu.device(), gpu.queue(), tick_encoder, "Offscreen Commands");
        }

        wgpuDevicePoll(gpu.device(), false, nullptr);
        frame_count++;
        return true;
    };

#ifdef __APPLE__
    auto poll_events = [&]() -> bool {
        glfwPollEvents();
        return !glfwWindowShouldClose(window);
    };
    vivid::macos_run_frame_loop(poll_events, tick_frame);
#else
    while (true) {
        glfwPollEvents();
        if (glfwWindowShouldClose(window)) break;
        if (!tick_frame()) break;
    }
#endif

    // Cleanup
    if (has_audio) audio_engine.shutdown();
    runtime.shutdown();
    blit.shutdown();
    gpu.shutdown();
    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
