// ColorBands fragment shader.
//
// The Uniforms struct, vertex shader, sampler, and fullscreen-triangle
// helper are all auto-generated by WgslFilterBase. Each Param<T>
// declared on the C++ side becomes a uniform field of the same name —
// always emitted as f32 (so int-typed params are read with i32(u.x)).
//
// WgslFilterBase doesn't support array uniforms, so the 6-color palette
// is unrolled into 18 individual c{0..5}_{r,g,b} float params and
// reconstructed here at the start of fs_main.

@fragment
fn fs_main(input: VertexOutput) -> @location(0) vec4f {
    let n = clamp(i32(u.band_count), 2, 6);
    let n_f = f32(n);

    // Pick the axis we vary along: 0 = horizontal stripes (vary by Y),
    // 1 = vertical stripes (vary by X).
    var coord = input.uv.y;
    if (i32(u.orientation) > 0) { coord = input.uv.x; }

    let pos    = fract(coord + u.time * u.scroll_speed);
    let band_f = pos * n_f;
    let band_i = i32(floor(band_f));
    let frac   = band_f - floor(band_f);

    let idx_a = ((band_i % n) + n) % n;
    let idx_b = (idx_a + 1) % n;

    // Reconstruct the palette from individual uniform floats. `var` array
    // (not `let`) so we can index it dynamically.
    var palette = array<vec3f, 6>(
        vec3f(u.c0_r, u.c0_g, u.c0_b),
        vec3f(u.c1_r, u.c1_g, u.c1_b),
        vec3f(u.c2_r, u.c2_g, u.c2_b),
        vec3f(u.c3_r, u.c3_g, u.c3_b),
        vec3f(u.c4_r, u.c4_g, u.c4_b),
        vec3f(u.c5_r, u.c5_g, u.c5_b),
    );
    let color_a = palette[idx_a];
    let color_b = palette[idx_b];

    // Soft edge: blend across the trailing softness fraction of each band.
    let soft = clamp(u.softness, 0.0, 1.0);
    let edge_threshold = 1.0 - soft * 0.5;
    let blend = smoothstep(edge_threshold, 1.0, frac);

    let color = mix(color_a, color_b, blend);
    return vec4f(color, 1.0);
}
