#!/usr/bin/env python3
"""Module-layering guard (static; no build) — ADR-0043 enforcement, option (c).

app/src/ is split into domain modules, but the split is directory convention with no
compiler/link enforcement, so a change can pull in unrelated modules and nothing stops a new
"wrong-direction" edge (the Phase-1 audit found app/ <-> ui/ <-> gpu/ header cycles, an
audio/ -> app/ RT include, a gpu/ <-> packages/ cycle). ADR-0043 codifies one allowed
direction: edges point DOWN the layer stack only.

This guard parses every `#include "<module>/..."` under app/src and flags UPWARD edges (a lower
layer including a higher one). Because the codebase has pre-existing violations that are out of
scope to fix now (ADR-0043: break cycles opportunistically), it works as a RATCHET: the current
violations are grandfathered in a baseline file, and only edges NOT in the baseline fail. A new
wrong-direction include fails CI; fixing one and removing its baseline line shrinks the debt.

Layer ranks (higher = higher in the stack; an include is legal iff it points to an EQUAL-or-LOWER
rank). From ADR-0043's candidate stack; `packages` (which the ADR stub left unplaced) sits just
below the engine so the gpu<->packages cycle resolves as `packages -> gpu` being the back-edge to
remove — see the ADR.

Usage:
    uv run tools/check_module_layering.py                  # enforce (CI)
    uv run tools/check_module_layering.py --update-baseline # regenerate the baseline file
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "app" / "src"
BASELINE = ROOT / "tools" / "module_layering_baseline.txt"

# ADR-0043 layer stack. Equal rank = same layer (peer edges allowed). Include is a violation
# only when it points UPWARD (to a strictly higher rank).
LAYER_RANK = {
    "operator_api": 0,   # leaf SDK
    "midi": 0,           # leaf
    "platform": 10,      # downward-only OS seam
    "packages": 15,      # package loader/compiler service (below engine; see ADR-0043)
    "gpu": 20,           # engine
    "audio": 20,         # engine
    "ui": 30,            # view
    "app": 40,           # composition / shell
    "cli": 50,           # control adapter (top)
}
MODULES = set(LAYER_RANK)
SRC_SUFFIXES = {".cpp", ".h", ".hpp", ".mm", ".c", ".inl"}
_INC = re.compile(r'#\s*include\s*"([a-z_]+)/[^"]+"')


def violations() -> list[tuple[str, str, str, str]]:
    """Return (src_module, dst_module, src_relpath, included_path) for every upward include."""
    out = []
    for p in SRC.rglob("*"):
        if not p.is_file() or p.suffix not in SRC_SUFFIXES:
            continue
        rel = p.relative_to(SRC)
        src_mod = rel.parts[0]
        if src_mod not in MODULES:
            continue
        for line in p.read_text(errors="ignore").splitlines():
            m = _INC.match(line.strip())
            if not m:
                continue
            inc = line.strip().split('"')[1]
            dst_mod = m.group(1)
            if dst_mod in MODULES and dst_mod != src_mod and LAYER_RANK[dst_mod] > LAYER_RANK[src_mod]:
                out.append((src_mod, dst_mod, str(rel), inc))
    return out


def _key(v) -> str:
    # Baseline granularity = (source file, included header): a NEW upward include in ANY file
    # (new file or new line) is caught even if that module-pair edge already exists elsewhere.
    return f"{v[2]} -> {v[3]}"


def load_baseline() -> set[str]:
    if not BASELINE.exists():
        return set()
    return {ln.split("#", 1)[0].strip() for ln in BASELINE.read_text().splitlines()
            if ln.strip() and not ln.strip().startswith("#")}


def write_baseline(vs) -> None:
    lines = sorted(f"{_key(v)}   # {v[0]} -> {v[1]} (upward)" for v in vs)
    header = (
        "# ADR-0043 module-layering baseline — grandfathered upward includes (out of scope to fix\n"
        "# now; break opportunistically). Generated by tools/check_module_layering.py\n"
        "# --update-baseline. Each line is `<src file> -> <included header>`. REMOVE a line when you\n"
        "# fix that edge; NEVER add lines by hand to silence a new violation — fix the include.\n"
    )
    BASELINE.write_text(header + "\n".join(lines) + "\n")


def main(argv) -> int:
    vs = violations()
    keys = {_key(v): v for v in vs}
    if "--update-baseline" in argv:
        write_baseline(vs)
        print(f"wrote {len(vs)} grandfathered edges to {BASELINE.relative_to(ROOT)}")
        return 0

    baseline = load_baseline()
    new = sorted(k for k in keys if k not in baseline)
    stale = sorted(baseline - set(keys))  # baselined edges that no longer exist (fixed)

    print(f"upward includes: {len(vs)} total | baselined: {len(baseline)} | "
          f"new: {len(new)} | fixed-but-still-baselined: {len(stale)}")
    if stale:
        print("\nThese baseline entries are now fixed — delete them to keep the ratchet tight:")
        for k in stale:
            print(f"  {k}")
    if new:
        print("\nFAIL — new upward (wrong-direction) module includes (ADR-0043):", file=sys.stderr)
        for k in new:
            src_mod, dst_mod = keys[k][0], keys[k][1]
            print(f"  [{src_mod} -> {dst_mod}] {k}", file=sys.stderr)
        print("\nRoute through a lower/equal layer, or move the shared header down. Do NOT add it to "
              "the baseline to silence this.", file=sys.stderr)
        return 1
    print("PASS — no new wrong-direction module includes")
    return 0


def test_no_new_layering_violations():
    vs = violations()
    new = sorted(_key(v) for v in vs if _key(v) not in load_baseline())
    assert not new, "new upward module includes (ADR-0043):\n  " + "\n  ".join(new)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
