// Headless test for P2b "Clone & Edit a built-in": prove the *real* clone template
// (the WGSL Plasma reproduction generated by operator_clone) compiles via the package
// compiler and registers into the OpRegistry through the operator loader — the two risky
// steps of clone_operator, exercised without a live App or GPU. (The pipeline is created
// lazily in process_gpu, which registration never calls, so no wgpu device is needed;
// the guarded destructor touches no wgpu when the instance was never initialized.)
#include "app/operator_clone.h"
#include "packages/package_manager.h"
#include "gpu/operator_loader.h"
#include "gpu/operator_scan.h"
#include "gpu/op_runtime.h"
#include "test_helpers.h"

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <memory>
#include <string>
#include <vector>

int main() {
    using namespace vivid;
    namespace fs = std::filesystem;

    // Only Plasma has a clone template today; a non-cloneable built-in yields empty source.
    CHECK(operator_has_clone_template("Plasma"));
    CHECK(!operator_has_clone_template("Blur"));
    CHECK(clone_operator_source("Blur", "BlurClone").empty());

    // Generate the real source + manifest the GUI path would write.
    const std::string type = "PlasmaClone";
    const std::string src = clone_operator_source("Plasma", type);
    CHECK(!src.empty());
    CHECK(src.find("__OPNAME__") == std::string::npos);        // placeholder fully substituted
    CHECK(src.find("struct PlasmaClone") != std::string::npos);
    CHECK(src.find("VIVID_REGISTER(PlasmaClone)") != std::string::npos);

    // Scaffold a package dir exactly like clone_operator does.
    const fs::path pkg = fs::temp_directory_path() / "vivid_clone_test_pkg";
    fs::remove_all(pkg);
    fs::create_directories(pkg);
    { std::ofstream(pkg / (type + ".cpp"), std::ios::trunc) << src; }
    { std::ofstream(pkg / "vivid-package.json", std::ios::trunc) << clone_operator_manifest(type); }

    // Install: compile the GPU operator into a temp managed dir.
    const std::string out = (fs::temp_directory_path() / "vivid_clone_test_out").string();
    fs::remove_all(out);
    setenv("VIVID_OPERATORS_DIR", out.c_str(), 1);
    PackageInstallResult r = install_package(pkg.string());
    CHECK(r.ok);
    CHECK(r.compiles.size() == 1);
    if (!r.compiles.empty() && !r.compiles[0].success)
        std::fprintf(stderr, "  compile error:\n%s\n", r.compiles[0].error_output.c_str());
    CHECK(!r.compiles.empty() && r.compiles[0].success);
    CHECK(!r.compiles.empty() && fs::exists(r.compiles[0].dylib_path));

    // Load + register the produced dylib — proves the clone ABI matches the host.
    OpRegistry reg;
    std::vector<std::unique_ptr<OperatorLoader>> loaders;
    const std::string name = load_and_register_operator(r.compiles[0].dylib_path, reg, loaders);
    CHECK(name == type);
    CHECK(reg.has(type));
    const VividOperatorDescriptor* d = reg.descriptor_for(type);
    CHECK(d != nullptr);
    CHECK(d && d->param_count == 4u);   // warp, hue, density, glow

    fs::remove_all(out);
    fs::remove_all(pkg);
    return vivid::test::summary("test_operator_clone");
}
